/** @format */

const Years = ['2017', '2018', '2019', '2020']
const Customers = ['Müller', 'Maier', 'Hofmann', 'Baumann']
const Products = ['AZ12', 'AV54', 'DF19', 'WZ12']
const Machines = ['ZS123', 'ZS234', 'XY124', 'XY432']
const Values = [30, 50, 10, 60]

export default [
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
  {
    year: Years[Math.floor(Math.random() * Years.length)],
    customer: Customers[Math.floor(Math.random() * Customers.length)],
    product: Products[Math.floor(Math.random() * Products.length)],
    machine: Machines[Math.floor(Math.random() * Machines.length)],
    value: Values[Math.floor(Math.random() * Products.length)],
  },
]
